export const FETCH_BRANCHES_STARTED = 'FETCH_BRANCHES_STARTED';
export const FETCH_BRANCHES_COMPLETED = 'FETCH_BRANCHES_COMPLETED';
export const FETCH_BRANCHES_FAILED = 'FETCH_BRANCHES_FAILED';

export const FETCH_BRANCH_STARTED = 'FETCH_BRANCH_STARTED';
export const FETCH_BRANCH_COMPLETED = 'FETCH_BRANCH_COMPLETED';
export const FETCH_BRANCH_FAILED = 'FETCH_BRANCH_FAILED';

export const ADD_BRANCH_STARTED = 'ADD_BRANCH_STARTED';
export const ADD_BRANCH_COMPLETED = 'ADD_BRANCH_COMPLETED';
export const ADD_BRANCH_FAILED = 'ADD_BRANCH_FAILED';

export const UPDATE_BRANCH_STARTED = 'UPDATE_BRANCH_STARTED';
export const UPDATE_BRANCH_COMPLETED = 'UPDATE_BRANCH_COMPLETED';
export const UPDATE_BRANCH_FAILED = 'UPDATE_BRANCH_FAILED';

export const REMOVE_BRANCH_STARTED = 'REMOVE_BRANCH_STARTED';
export const REMOVE_BRANCH_COMPLETED = 'REMOVE_BRANCH_COMPLETED';
export const REMOVE_BRANCH_FAILED = 'REMOVE_BRANCH_FAILED';

export const SELECT_BRANCH = 'SELECT_BRANCH';
export const DESELECT_BRANCH = 'DESELECT_BRANCH';