export const MENU_FETCH_STARTED = 'MENU_FETCH_STARTED';
export const MENU_FETCH_COMPLETED = 'MENU_FETCH_COMPLETED';
export const MENU_FETCH_FAILED = 'MENU_FETCH_FAILED';

export const MENU_ADD_STARTED = 'MENU_ADD_STARTED';
export const MENU_ADD_COMPLETED = 'MENU_ADD_COMPLETED';
export const MENU_ADD_FAILED = 'MENU_ADD_FAILED';

export const MENU_REMOVE_STARTED = 'MENU_REMOVE_STARTED';
export const MENU_REMOVE_COMPLETED = 'MENU_REMOVE_COMPLETED';
export const MENU_REMOVE_FAILED = 'MENU_REMOVE_FAILED';

export const MENU_SELECTED = 'MENU_SELECTED';
export const MENU_DESELECTED = 'MENU_DESELECTED';