export const OFFER_FETCH_STARTED = 'OFFER_FETCH_STARTED';
export const OFFER_FETCH_COMPLETED = 'OFFER_FETCH_COMPLETED';
export const OFFER_FETCH_FAILED = 'OFFER_FETCH_FAILED';

export const OFFER_ADD_STARTED = 'OFFER_ADD_STARTED';
export const OFFER_ADD_COMPLETED = 'OFFER_ADD_COMPLETED';
export const OFFER_ADD_FAILED = 'OFFER_ADD_FAILED';
export const OFFER_ADD_CLEAR = 'OFFER_ADD_CLEAR';

export const OFFER_EDIT_STARTED = 'OFFER_EDIT_STARTED';
export const OFFER_EDIT_COMPLETED = 'OFFER_EDIT_COMPLETED';
export const OFFER_EDIT_FAILED = 'OFFER_EDIT_FAILED';

export const OFFER_REMOVE_STARTED = 'OFFER_REMOVE_STARTED';
export const OFFER_REMOVE_COMPLETED = 'OFFER_REMOVE_COMPLETED';
export const OFFER_REMOVE_FAILED = 'OFFER_REMOVE_FAILED';