export const PRODUCT_FETCH_STARTED = 'PRODUCT_FETCH_STARTED';
export const PRODUCT_FETCH_COMPLETED = 'PRODUCT_FETCH_COMPLETED';
export const PRODUCT_FETCH_FAILED = 'PRODUCT_FETCH_FAILED';

export const PRODUCT_ADD_STARTED = 'PRODUCT_ADD_STARTED';
export const PRODUCT_ADD_COMPLETED = 'PRODUCT_ADD_COMPLETED';
export const PRODUCT_ADD_FAILED = 'PRODUCT_ADD_FAILED';

export const PRODUCT_EDIT_STARTED = 'PRODUCT_EDIT_STARTED';
export const PRODUCT_EDIT_COMPLETED = 'PRODUCT_EDIT_COMPLETED';
export const PRODUCT_EDIT_FAILED = 'PRODUCT_EDIT_FAILED';

export const PRODUCT_REMOVE_STARTED = 'PRODUCT_REMOVE_STARTED';
export const PRODUCT_REMOVE_COMPLETED = 'PRODUCT_REMOVE_COMPLETED';
export const PRODUCT_REMOVE_FAILED = 'PRODUCT_REMOVE_FAILED';

export const PRODUCT_SELECTED = 'PRODUCT_SELECTED';
export const PRODUCT_DESELECTED = 'PRODUCT_DESELECTED';