export const FETCH_RESTAURANTS_STARTED = 'FETCH_RESTAURANTS_STARTED';
export const FETCH_RESTAURANTS_COMPLETED = 'FETCH_RESTAURANTS_COMPLETED';
export const FETCH_RESTAURANTS_FAILED = 'FETCH_RESTAURANTS_FAILED';

export const FETCH_RESTAURANT_STARTED = 'FETCH_RESTAURANT_STARTED';
export const FETCH_RESTAURANT_COMPLETED = 'FETCH_RESTAURANT_COMPLETED';
export const FETCH_RESTAURANT_FAILED = 'FETCH_RESTAURANT_FAILED';

export const ADD_RESTAURANT_STARTED = 'ADD_RESTAURANT_STARTED';
export const ADD_RESTAURANT_COMPLETED = 'ADD_RESTAURANT_COMPLETED';
export const ADD_RESTAURANT_FAILED = 'ADD_RESTAURANT_FAILED';

export const UPDATE_RESTAURANT_STARTED = 'UPDATE_RESTAURANT_STARTED';
export const UPDATE_RESTAURANT_COMPLETED = 'UPDATE_RESTAURANT_COMPLETED';
export const UPDATE_RESTAURANT_FAILED = 'UPDATE_RESTAURANT_FAILED';

export const REMOVE_RESTAURANT_STARTED = 'REMOVE_RESTAURANT_STARTED';
export const REMOVE_RESTAURANT_COMPLETED = 'REMOVE_RESTAURANT_COMPLETED';
export const REMOVE_RESTAURANT_FAILED = 'REMOVE_RESTAURANT_FAILED';

export const SELECT_RESTAURANT = 'SELECT_RESTAURANT';
export const DESELECT_RESTAURANT = 'DESELECT_RESTAURANT';