export const USERS_FETCH_STARTED = 'USERS_FETCH_STARTED';
export const USERS_FETCH_COMPLETED = 'USERS_FETCH_COMPLETED';
export const USERS_FETCH_FAILED = 'USERS_FETCH_FAILED';

export const USER_ADD_STARTED = 'USER_ADD_STARTED';
export const USER_ADD_COMPLETED = 'USER_ADD_COMPLETED';
export const USER_ADD_FAILED = 'USER_ADD_FAILED';
export const USER_ADD_CLEAR = 'USER_ADD_CLEAR';

export const USER_EDIT_STARTED = 'USER_EDIT_STARTED';
export const USER_EDIT_COMPLETED = 'USER_EDIT_COMPLETED';
export const USER_EDIT_FAILED = 'USER_EDIT_FAILED';

export const USER_REMOVE_STARTED = 'USER_REMOVE_STARTED';
export const USER_REMOVE_COMPLETED = 'USER_REMOVE_COMPLETED';
export const USER_REMOVE_FAILED = 'USER_REMOVE_FAILED';

export const USER_SELECTED = 'USER_SELECTED';
export const USER_DESELECTED = 'USER_DESELECTED';